# Test Configuration for Anthropic Format

name: "Test LiteLLM Proxy"
version: "1.0.0"
schema: "v1"

models:
  - name: "claude-sonnet-4-test"
    provider: anthropic
    model: anthropic/claude-sonnet-4-20250514
    apiBase: http://localhost:8009  # Continue.dev adds /messages automatically
    apiKey: "dummy-key-not-used"
    roles:
      - chat
      - edit
    requestOptions:
      extraBodyProperties:
        thinking:
          type: "enabled"
          budget_tokens: 2048
    defaultCompletionOptions:
      contextLength: 200000
      maxTokens: 30000
      temperature: 0.7
    capabilities:
      - tool_use
      - image_input

context:
  - provider: file
  - provider: terminal
  - provider: problems
  - provider: tree
  - provider: code
  - provider: diff

# Minimal config for testing
rules: []
prompts: []
docs: []
